numero1 = int(input("Digite o primeiro número inteiro: "))
numero2 = int(input("Digite o segundo número inteiro: "))
numero3 = int(input("Digite o terceiro número inteiro: "))
numero4 = int(input("Digite o quarto número inteiro: "))
numero5 = int(input("Digite o quinto número inteiro: "))
menor_numero = min(numero1,numero2,numero3,numero4,numero5)
maior_numero =max(numero1,numero2,numero3,numero4,numero5)
print(f"O menor número entre {numero1}, {numero2} , {numero3} ,{numero4} e {numero5} é {menor_numero}.")
print(f"O maior número entre {numero1}, {numero2} , {numero3} ,{numero4} e {numero5} é {maior_numero}.")